In [1]:
import numpy as np

List vs Array :

* list : list are data container objects that are ordered , mutable and heterogeneous. This makes them extremely flexible and they provide high utility when one wants to just group a collection of objects together without needing to wory about the data types.
List  actually don't contain any object,but instead they contain mapping /pointers to object that are stored at various location within the memory.
They are no contigiously stored hence takes time to access each time.

* Array : Here the data is stored contigiously (as a block of data) and resulting in one dimensional basic array.It may be less flexible but more accessible make computation faster.

axis 1: -----> horizontal

axis 0 : vertical

## Creating Array using predefined values :

* Using list :

In [2]:
l=[1,2,3]
a=np.array(l)
a,type(a),type(a[0])

(array([1, 2, 3]), numpy.ndarray, numpy.int32)

In [3]:
## using specific datatype
a1=np.array(l,dtype='int64')
a1

array([1, 2, 3], dtype=int64)

In [4]:
l=[0.1,2,3]
a1=np.array(l)
a1,type(a[0])

(array([0.1, 2. , 3. ]), numpy.int32)

* Using arange function : arange() <br>
it creates an array of values of the specified range.

In [5]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [6]:
a1=np.arange(5,20,3)
a1

array([ 5,  8, 11, 14, 17])

* Using Linspace function : <b>linspace(start,end,num_of)</b> <br>
create the required no. of equispaced values within a defined interval/range.

In [7]:
a=np.linspace(22,22.5,3)
a

array([22.  , 22.25, 22.5 ])

In [8]:
a1=np.linspace(0,3,5)
a1

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

* Using only Ones : ones / ones_like /zeros /zeros_like<br>  
used to create array containing only ones.


In [9]:
a=np.ones(1)
a

array([1.])

In [10]:
a1=np.ones([2,4])  # (shape)
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
l=[1,2,4,5]
a2=np.ones_like(l)
a2

array([1, 1, 1, 1])

In [12]:
a3=np.ones_like(a1)
a3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Creating Array using Random Number Generator :

In [13]:
a=np.random.rand(3) # random float b/w zero and one 
a

array([0.32946717, 0.64396741, 0.4973138 ])

In [14]:
a=np.random.randint(1,10,5) # (max,min,no.of values) : create random integers
a


array([9, 1, 5, 8, 5])

In [15]:
a=np.random.randint(1,10,(2,5))
a

array([[6, 4, 1, 7, 3],
       [3, 5, 2, 7, 9]])

In [16]:
### Using randn : array containing random no. sampled from a std gaussian/normal distribution .
a=np.random.randn(3)
a

array([ 0.58059229, -1.28371808,  0.68803893])

In [17]:
a=np.random.randn(2,3) #(shape)
a

array([[ 0.79565239, -0.36426051,  0.31727836],
       [ 0.46190927, -1.57831977, -1.43311199]])

#### Indexing and slicing :

In [18]:
a=np.random.randint(1,100,[3,4])
a

array([[28, 10, 83, 75],
       [75, 28, 78, 64],
       [19, 80, 92,  7]])

In [19]:
a[0],a[-1]

(array([28, 10, 83, 75]), array([19, 80, 92,  7]))

In [20]:
a[0][0],a[0][1]

(28, 10)

## array attributes :

In [21]:
a.dtype  # data type of element stored

dtype('int32')

In [22]:
a.ndim  # no. of axis

2

In [23]:
a.shape # shape

(3, 4)

## array methods :

In [24]:
a=np.random.randint(1,100,6)
a

array([54, 23,  4, 56, 14, 67])

In [25]:
a.resize(2,3)
a

array([[54, 23,  4],
       [56, 14, 67]])

In [26]:
a.shape

(2, 3)

In [27]:
a.reshape(1,-1)

array([[54, 23,  4, 56, 14, 67]])

In [28]:
a.reshape(-1,1)

array([[54],
       [23],
       [ 4],
       [56],
       [14],
       [67]])

In [29]:
a=np.random.randint(1,100,[2,3])
a

array([[43, 79, 16],
       [17, 51, 52]])

In [30]:
a1=a.flatten()
a1

array([43, 79, 16, 17, 51, 52])

In [31]:
a.shape,a1.shape

((2, 3), (6,))

In [32]:
#### sort and argsort

# argsort : return the indices that would sort the array it was applied to

In [33]:
a=np.random.randint(1,100,5)
a

array([80, 74, 29, 99,  2])

In [34]:
a1=a.sort()
a1

In [35]:
i=a.argsort()
i

array([0, 1, 2, 3, 4], dtype=int64)

In [36]:
## sort element in decending order :

In [37]:
a=np.arange(11,100,10)
a

array([11, 21, 31, 41, 51, 61, 71, 81, 91])

In [38]:
a.sort()
a1=a[-1::-1]
a1

array([91, 81, 71, 61, 51, 41, 31, 21, 11])

In [39]:
## Nonzero : return indices of the element in array that are non-zero.

In [40]:
a=np.random.randint(0,4,5)
a.nonzero()

(array([0, 2, 3, 4], dtype=int64),)

In [41]:
## max and argmax :

In [42]:
a=np.random.randint(1,100,[3,5])
a

array([[88, 60, 12, 24, 52],
       [91, 60,  9,  2, 35],
       [89, 72, 21, 81, 11]])

In [43]:
a.max() , a.max(axis=0) , a.max(axis=1) # max() : return max value along the given axis.

(91, array([91, 72, 21, 81, 52]), array([88, 91, 89]))

In [44]:
a.argmax(), a.argmax(axis=0) , a.argmax(axis=1) # argmax() : return the indexes of max value along any given axis.

(5, array([1, 2, 2, 2, 0], dtype=int64), array([0, 0, 0], dtype=int64))

In [45]:
## sum and cumsum :

In [46]:
a=np.random.randint(1,100,[3,5])
a

array([[14, 12, 91, 97, 60],
       [64, 63, 93, 92,  5],
       [83, 40, 10, 18, 49]])

In [47]:
a.sum() , a.sum(axis=0) , a.sum(axis=1)

(791, array([161, 115, 194, 207, 114]), array([274, 317, 200]))

In [48]:
## cumsum  : return the cumulative sum of the array  element over any given axis.

In [49]:
a=np.random.randint(1,100,[2,2])
a

array([[58, 21],
       [33, 94]])

In [50]:
a.cumsum(axis=0)

array([[ 58,  21],
       [ 91, 115]])

In [51]:
a.cumsum(axis=1)

array([[ 58,  79],
       [ 33, 127]])

In [52]:
a.cumsum()

array([ 58,  79, 112, 206])

In [53]:
## prod and cumprod : return the product and cumulative product of the array element over any give axis.

In [54]:
a=np.random.randint(1,100,[2,3])
a

array([[ 6, 16, 83],
       [73, 15, 40]])

In [55]:
a.prod() , a.prod(axis=0),a.prod(axis=1)


(348998400, array([ 438,  240, 3320]), array([ 7968, 43800]))

In [56]:
a.cumprod()

array([        6,        96,      7968,    581664,   8724960, 348998400])

In [57]:
a.cumprod(axis=0)

array([[   6,   16,   83],
       [ 438,  240, 3320]])

In [58]:
a.cumprod(axis=1)

array([[    6,    96,  7968],
       [   73,  1095, 43800]])

In [59]:
### mean , var , std 

In [60]:
a=np.random.randint(1,100,[2,3])
a

array([[17, 36, 89],
       [42, 39, 79]])

In [61]:
a.mean() , a.mean(axis=0) , a.mean(axis=1)

(50.333333333333336,
 array([29.5, 37.5, 84. ]),
 array([47.33333333, 53.33333333]))

In [62]:
a.var() , a.var(axis=0) , a.var(axis=1)

(638.5555555555555,
 array([156.25,   2.25,  25.  ]),
 array([928.22222222, 330.88888889]))

In [63]:
a.std() , a.std(axis=0) , a.std(axis=1)

(25.269656815151954,
 array([12.5,  1.5,  5. ]),
 array([30.46673961, 18.19035153]))

## Unary functions :

In [64]:
a=np.random.randint(-100,100,[2,3])
a

array([[ 22,  60,  73],
       [ 94, -54, -71]])

In [65]:
np.abs(a)

array([[22, 60, 73],
       [94, 54, 71]])

In [66]:
np.square(a)

array([[ 484, 3600, 5329],
       [8836, 2916, 5041]])

In [67]:
a=np.array([[1.5,2.22,11.95]])
a

array([[ 1.5 ,  2.22, 11.95]])

In [68]:
np.ceil(a) # compute smallest integer greater than or equal to a given no. for every element in array

array([[ 2.,  3., 12.]])

In [69]:
np.floor(a) # compute the largest integer lesser than or equal to a given no. for every element in array

array([[ 1.,  2., 11.]])

In [70]:
np.sqrt(a),
np.exp(a),
np.log(a)
np.log2(a)
np.log10(a)

array([[0.17609126, 0.34635297, 1.07736791]])

## Linear Algebra :

In [71]:
a=np.random.rand(3,3)
a

array([[0.58497156, 0.97565766, 0.45858212],
       [0.42821611, 0.16046271, 0.46574198],
       [0.748651  , 0.27224696, 0.85580364]])

In [72]:
np.diag(a) # diagonal elements 

array([0.58497156, 0.16046271, 0.85580364])

In [73]:
np.trace(a) # return sum of element of diagonal

1.601237905490125

In [74]:
np.transpose(a) # transpose of matrix    

array([[0.58497156, 0.42821611, 0.748651  ],
       [0.97565766, 0.16046271, 0.27224696],
       [0.45858212, 0.46574198, 0.85580364]])

In [75]:
a.T

array([[0.58497156, 0.42821611, 0.748651  ],
       [0.97565766, 0.16046271, 0.27224696],
       [0.45858212, 0.46574198, 0.85580364]])

## L1 and L2 Norm :

The norm function return the norm of an array along any axis specified. Norms are a way to quantify the magnitude of a one dim array (vector).

* Two norm type relevant for our purpose are L1 and L2 norms.
* L1 norm : It is the sum of absolute values of each element of the vector.
* L2 norm : It is the square root of the sum of the square of each element in vector.

In [76]:
# L2 norms :
np.linalg.norm(a,2)

1.7077295291625587

In [77]:
np.linalg.norm(a,2,axis=0)

array([1.04213198, 1.0255606 , 1.0768533 ])

In [78]:
np.linalg.norm(a,2,axis=1)

array([1.22653868, 0.65271197, 1.16918629])

#### L1 Norm :

In [79]:
np.linalg.norm(a,1)

1.780127738226307

In [80]:
np.linalg.norm(a,1,axis=0)

array([1.76183866, 1.40836733, 1.78012774])

In [81]:
np.linalg.norm(a,1,axis=1)

array([2.01921133, 1.0544208 , 1.8767016 ])

#### Dot product :

In [82]:
a1=np.random.rand(3)
a2=np.random.rand(3)
a1,a2

(array([0.76906849, 0.9442091 , 0.62881577]),
 array([0.50469902, 0.83850094, 0.29704791]))

In [83]:
a_dot=(a1*a2).sum()
a_dot

1.366656733933374

In [84]:
np.dot(a1,a2)

1.366656733933374

In [85]:
a1 @ a2

1.366656733933374

#### Matrix Multiplication :

In [86]:
m1=np.random.randint(1,100,[2,3])
m2=np.random.randint(50,75,[3,5])


In [87]:
m1

array([[44, 83, 19],
       [65, 90, 59]])

In [88]:
m2

array([[55, 59, 74, 66, 71],
       [62, 74, 62, 55, 52],
       [66, 70, 66, 58, 68]])

In [89]:
m_prod=m1@m2
m_prod

array([[ 8820, 10068,  9656,  8571,  8732],
       [13049, 14625, 14284, 12662, 13307]])

#### Concatenation of Array :

In [90]:
m1=np.random.randint(1,100,[2,3])
v1=np.random.randint(10,50,[1,3])
v2=np.random.randint(10,50,[3,1])

In [91]:
m1

array([[88, 74,  1],
       [19, 51, 76]])

In [92]:
v1

array([[29, 20, 12]])

In [93]:
v2

array([[37],
       [37],
       [33]])

* Row wise Conatenation :

In [94]:
m2=np.concatenate((m1,v1),axis=0)
m2

array([[88, 74,  1],
       [19, 51, 76],
       [29, 20, 12]])

In [95]:
np.vstack((m1,v1))

array([[88, 74,  1],
       [19, 51, 76],
       [29, 20, 12]])

* Column wise Concatenate :

In [96]:
np.concatenate((m2,v2),axis=1)

array([[88, 74,  1, 37],
       [19, 51, 76, 37],
       [29, 20, 12, 33]])

In [97]:
np.hstack((m2,v2))

array([[88, 74,  1, 37],
       [19, 51, 76, 37],
       [29, 20, 12, 33]])

* Saving and loading numpy data

In [98]:
a=np.random.randint(1,100,[3,5])
a

array([[57,  6, 71, 73, 69],
       [30, 49, 59, 79, 40],
       [67, 78, 21, 55, 87]])

In [99]:
name='array_a.npy'
np.save(name,a)

In [100]:
a=np.load('array_a.npy')
a

array([[57,  6, 71, 73, 69],
       [30, 49, 59, 79, 40],
       [67, 78, 21, 55, 87]])

# Pandas 

In [101]:
import pandas as pd

In [102]:
a=np.random.randint(1,100,5)
s=pd.Series(a)
s

0    53
1    16
2    85
3    24
4    31
dtype: int32

In [103]:
s.values

array([53, 16, 85, 24, 31])

In [104]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [105]:
i1=['a','b','c','d','e']
s1=pd.Series(a,index=i1)
s1

a    53
b    16
c    85
d    24
e    31
dtype: int32

In [106]:
s1[1:-2]

b    16
c    85
dtype: int32

In [107]:
s1['b':'d']

b    16
c    85
d    24
dtype: int32

In [108]:
people=['bob','sam','john','sally','kim']
weights=[70,97,63,50,65]

d={k:v for k, v in zip(people,weights)}
s=pd.Series(d)
s

bob      70
sam      97
john     63
sally    50
kim      65
dtype: int64

In [109]:
pd.Series(weights,index=people)

bob      70
sam      97
john     63
sally    50
kim      65
dtype: int64

In [110]:
s['sam':'kim']

sam      97
john     63
sally    50
kim      65
dtype: int64

In [111]:
# attribues
s.max(), s.min(), s.mean(),s.var(),s.std() ,s.sum(),s.prod(),s.cumsum(),s.cumprod()

(97,
 50,
 69.0,
 299.5,
 17.30606829987678,
 345,
 1390252500,
 bob       70
 sam      167
 john     230
 sally    280
 kim      345
 dtype: int64,
 bob              70
 sam            6790
 john         427770
 sally      21388500
 kim      1390252500
 dtype: int64)

In [112]:
d1=dict(sam=[60,52,5.9],
        jill=[55,46,5.4],
        kate=[19,60,5.8],
        jack=[36,89,6.3])
d1

{'sam': [60, 52, 5.9],
 'jill': [55, 46, 5.4],
 'kate': [19, 60, 5.8],
 'jack': [36, 89, 6.3]}

In [113]:
d2=dict(age=[60,55,19,36],
        weight=np.random.randint(1,100,4),
        height=np.random.uniform(4.1,5.1,4).round()
)
d2

{'age': [60, 55, 19, 36],
 'weight': array([28, 18, 50, 14]),
 'height': array([5., 5., 4., 5.])}

In [114]:
df=pd.DataFrame(d2)
df

age  weight  height
0   60      28     5.0
1   55      18     5.0
2   19      50     4.0
3   36      14     5.0

In [115]:
df=pd.DataFrame(d2,index=d1.keys())
df

age  weight  height
sam    60      28     5.0
jill   55      18     5.0
kate   19      50     4.0
jack   36      14     5.0

In [116]:
index1=pd.Index([1,2,4,6,7,9])
index1

Index([1, 2, 4, 6, 7, 9], dtype='int64')

In [117]:
index2=pd.Index([1,2,3,5,8,10])
index2

Index([1, 2, 3, 5, 8, 10], dtype='int64')

In [118]:
index1 | index2

idx_1 & idx_2

NameError: name 'idx_1' is not defined

In [ ]:
df

In [ ]:
name="sample_table.csv"
df.to_csv(name)

In [ ]:
df_cars=pd.read_csv("Automobile_data.csv")

In [ ]:
df_cars.shape

In [ ]:
df_cars.index

In [ ]:
df_cars.columns

In [ ]:
## Head and tail sampling method :

In [ ]:
df_cars.head(10)

In [ ]:
df_cars.tail(10)

In [ ]:
### Info method : gives info about datatypes and the non null value

In [ ]:
df_cars.info()

#### Describe :
Gives statical summary of all columns that contains numerical values. (count ,mean std,min,max,25th,50th and 75th percentile values )

In [ ]:
df_cars.describe()

In [ ]:
### DataFrame column attributes :

In [ ]:
df_cars.make

In [ ]:
df_cars.price

### Unique method :

In [ ]:
df_cars.make.unique()

### Value count :

In [ ]:
df_cars.make.value_counts()

### Plot Method :

In [ ]:
df_cars.make.value_counts().plot(kind='bar')

In [ ]:
### Histogram :
# df_cars.price.plot(kind='hist')

### scatter plot :
# df_cars.plot(x='hp',y='mpg',king='scatter')

### Drop method :

In [ ]:
df_cars.drop([1,2,5,7]).head()
# df_cars.drop(['drive','peak_rpm'],axis=1).head()

In [ ]:
### sort values : sort_values('column_name',ascending=False).head()
df_cars.sort_values('peak-rpm',ascending=False).head()

### Assign Method :
Used to create a new dataframe containing the same values as the orginal 
dataframe to which it was applied to but with new column assigned to it.

In [ ]:
df_cars2=df_cars.assign(mpg=np.random.randint(20,30))
df_cars2.head()

### The insert method :

In [ ]:
mpg=df_cars2['highway-mpg']

In [ ]:
#df_cars.insert(loc=5,column='mpg',value=mpg)
df_cars.head()

### groupby method:
groupby numerical columns to the categorical values.

In [ ]:
# df_drive=df_cars.groupby('drive-wheels').mean()
# df_drive

### Handling missing data :

In [ ]:
n=np.nan
n,type(n)

In [ ]:
l=[11,2,None,np.nan,5,772]
s=pd.Series(l)
s

In [ ]:
s.mean(),s.std()

In [ ]:
s.cumsum(),s.cumprod()

In [ ]:
df_cars.isna().sample(5) # isna() : true represent values missing

In [ ]:
null_cols=df_cars.isna().sum()
null_cols

### finding the rows are missing values :

In [ ]:
null_rows=df_cars.isna().sum(axis=1)
null_rows

In [ ]:
np.where(null_rows)

In [ ]:
## dropna method for droping columns with missing values

In [ ]:
df_cars.dropna().shape

In [ ]:
df_cars.dropna(axis=1).shape

In [ ]:
### fillna : used to fill missing values.

In [ ]:
s=pd.Series(l)
s

In [ ]:
s.fillna(0) ## filling with zeros

In [ ]:
s.fillna(s.median()) # filling with  median

## Data selection and slicing :

In [ ]:
df_cars.iloc[100:105,6:] ## rows 100t0 105 and column from 6 ownwards.

In [ ]:
df_cars.loc[100:105,'drive-wheels'] #selecting a named column (loc is used)

### Conditonal Slicing :

In [ ]:
cond=df_cars.make=='alfa-romero'
df_cars[cond]

In [ ]:
# cond1=df_cars.price<=6650
# cond2=df_cars.mpg>=df_cars.mpg.mean()
# df_cars[cond1 & cond2]

### Combining data frame :

1. Inner join : one combine row share data . 2 df share a column that descrive the same feature about the data.
2. Outer Join : it is combn of all rows in any one df and union of both the rows 

In [ ]:
df1=pd.DataFrame({'F1':range(5),'F2':[11,22,33,44,55]},index=['a','b','c','d','e'])
df1

In [ ]:
df2=pd.DataFrame({'F3':range(4),'F4':[111,222,333,444]},index=['A','B','Y','Z'])
df2

In [ ]:
df3=pd.merge(df1,df2,left_index=True,right_index=True)
df3 # Inner join

In [ ]:
### Apply fn:

In [ ]:
def exaple_fn(x):return (x**2)/2

df1=df1.apply(exaple_fn)
df1

### Feature Selection (Correlation):
feature selection done if there are soo many feature,mangable set of features that are importand than rese

In [ ]:
df.colums=['f'+str(i) for i in range(df.shape[1]-1)]+['labels']
df.head()  ## boston house data

this converted above in column name from f0 to f11 (i.e feature 0 to 11 ) and label

### correlation method:
computes correlation of every column in dataframe with every other column and represnt in form of correlation

In [ ]:
df_corr=df.corr().abs()
df_corr

In [ ]:
df_corr.style.background_gradient()

* dig ele : corresponds to dakest as they correlation with themselves.
* Objective of Feature selection using correlation :

1. We mant to choose thsoe feature(col) that are more correlated to the labels .(as we ulimately use them to predict colms) Hence we drop those feature that have a correlation lesser than some specified threshold.
2. We want to select those features that are not too correlated with each other, since a high degree of correlation b/w two feature that both are similar and only one of them would actually be necesary.

### we achive this as follows :

1. first create a copy of df_corr copy

In [ ]:
df_corr1=df_corr.copy().abs()

2. The 'label' column of df_corr1 contain the correlation of all the columns w.r.t labels. We first sort the labels in descending order

In [ ]:
# ser_label_corr=df_corr1.label.sort_values(ascending=False)
# ser_label_corr